---
- name: Installer Docker
  hosts: aws
  become: yes
  tasks:
    - name: Installer les dépendances Docker
      apt:
        update_cache: true
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'lsb-release']
        state: present

    - name: Ajout clé Docker GPG
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Ajout référentiel Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_lsb.codename }} stable
        state: present

    - name: Installer Docker
      apt:
        name: docker-ce
        state: present

    - name: Démarrer et activer le service Docker
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Installer Git
      apt:
        name: git
        state: present
