version: '3.1'

services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres"
    container_name: ${PG_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    volumes:
      - dbapp:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - reseau1

  web:
    image: apache_image:1.0
    networks:
      - reseau1
    ports:
      - "80:80"
      - "5432:5432"
    env_file:
      - .env
networks:
  reseau1:
    driver: bridge


volumes:
  dbapp:
    external: true
    
  
